development:
  adapter: postgresql
  encoding: unicode
  database: bc233_development
  pool: 5
  username: postgres
  password: 1]vASfa*RrW)qAa.

test:
  adapter: postgresql
  encoding: unicode
  database: bc233_test
  pool: 5
  username: postgres
  password: 1]vASfa*RrW)qAa.

production:
  adapter: postgresql
  encoding: unicode
  database: bc233_production
  pool: 5
  username: postgres
  password: 1]vASfa*RrW)qAa.
