development:
  adapter: postgresql
  encoding: unicode
  database: hellman233bc2
  pool: 5
  username: hellman233bc2
  password: zmg2hizx

test:
  adapter: postgresql
  encoding: unicode
  database: hellman233bc2
  pool: 5
  username: hellman233bc2
  password: zmg2hizx

production:
  adapter: postgresql
  encoding: unicode
  database: hellman233bc2
  pool: 5
  username: hellman233bc2
  password: zmg2hizx