development:
  adapter: postgresql
  encoding: unicode
  database: bc233_development
  pool: 5
  username: postgres
  password: ***

test:
  adapter: postgresql
  encoding: unicode
  database: bc233_test
  pool: 5
  username: postgres
  password: ***

production:
  adapter: postgresql
  encoding: unicode
  database: bc233_production
  pool: 5
  username: postgres
  password: ***
